module.exports = [
	{
		method: "cutAndPaste",
		description: "Take 2 or 3 consecutive words and move them to the end of the message",
		description_fr: "Coupe 2 ou 3 mots consécutifs et les colle à la fin de la phrase",
		initialChance: 15,
		repeatModifier: 0,
	},
	{
		method: "lowercase",
		description: "Lowercase the whole message",
		description_fr: "Passe tout le message en minuscules",
		initialChance: 60,
		repeatModifier: 0,
	},
	{
		method: "randomUppercase",
		description: "Uppercase the first letter of a random word",
		description_fr: "Passe la première lettre d'un mot aléatoire en majuscule",
		initialChance: 5,
		repeatModifier: .2,
	},
	{
		method: "moveSpace",
		description: "Move a space inside a adjacent word",
		description_fr: "Déplace une espace à l'intérieur d'un mot adjacent",
		initialChance: 90,
		repeatModifier: .4,
	},
	{
		method: "doubleSpace",
		description: "Double a random space",
		description_fr: "Double une espace aléatoire",
		initialChance: 60,
		repeatModifier: .5,
	},
	{
		method: "removePunctuation",
		description: "Remove a . or ,",
		description_fr: "Supprime un . ou une ,",
		initialChance: 50,
		repeatModifier: .5,
	},
	{
		method: "removePair",
		description: "Remove one from a pair of identical letters",
		description_fr: "Supprime une des deux d'une paire de lettres identiques",
		initialChance: 60,
		repeatModifier: .3,
	},
	{
		method: "wrongPair",
		description: "Mess up a pair of identical letters (door -> ddor/dorr)",
		description_fr: "Foire une paire de lettres identiques (puzzle -> puuzle/puzlle)",
		initialChance: 60,
		repeatModifier: .3,
	},
	{
		method: "swapLetters",
		description: "Swap two consecutive letters",
		description_fr: "Inverse deux lettres consécutives",
		initialChance: 40,
		repeatModifier: .3,
	},
	{
		method: "removeRandomLetter",
		description: "Remove a random letter",
		description_fr: "Supprime une lettre aléatoire",
		initialChance: 8,
		repeatModifier: .2,
	},
	{
		method: "originStory",
		description: "Replace the whole message with the one who started it all",
		description_fr: "Remplace tout le message par celui qui a fait naître ce bot",
		initialChance: 1,
		repeatModifier: 0,
	},
];
